# Generated by Django 6.0.4 on 2026-04-22 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('incomeRate', models.IntegerField(default=10)),
                ('maxCapacity', models.IntegerField(default=1000)),
                ('base_cost', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('coins', models.BigIntegerField(default=1000)),
                ('mtCoins', models.BigIntegerField(default=0)),
                ('promoCoins', models.BigIntegerField(default=0)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBuilding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('lastCollected', models.BigIntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.buildingtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
