# Generated by Django 6.0.4 on 2026-04-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_energy_profile_realbalance_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuilding',
            name='rotated',
            field=models.BooleanField(default=False),
        ),
    ]
